name: Test

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref,'refs/heads/release') && 'production' || 'development' }}

    steps:
      - run: |
          echo ${{ vars.SECURITY_GROUP }}


